### ISSUE TITLE
Exception reading .DS_Store file

### ISSUE THREAD

**Issue by tjheslin1** [tjheslin1/Westie#6]
Encountered an error running a static analysis check using `WestieDirectoryAnalyser` and the underlying `WestieCachedFileReader`.

Receive the following error trying to `readAllLines` of the .DS_Store file, due to a special character.

Solution:
- [x] Ignore hidden files. Should only check user written files.
- [x] Ignore hidden directories unless the top provided `pathToCheck` is a hidden directory (starting with a '.', e.g: ".git")
- [x] Report in error output the file which had the problem. 

```java
com.google.common.util.concurrent.UncheckedExecutionException: java.nio.charset.MalformedInputException: Input length = 1

	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5148)
	at io.github.tjheslin1.westie.infrastructure.WestieCachedFileReader.readAllLines(WestieCachedFileReader.java:60)
	at io.github.tjheslin1.westie.WestieDirectoryAnalyser.analyseFileLines(WestieDirectoryAnalyser.java:147)
	at io.github.tjheslin1.westie.WestieDirectoryAnalyser.lambda$analyseLinesOfFile$6(WestieDirectoryAnalyser.java:112)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.github.tjheslin1.westie.WestieDirectoryAnalyser.analyseLinesOfFile(WestieDirectoryAnalyser.java:113)
	at io.github.tjheslin1.westie.gitissue.GitIssueAnalyser.todosAreInOpenState(GitIssueAnalyser.java:81)
	at io.github.tjheslin1.westie.gitissue.GitIssueAnalyser.todosAreInOpenState(GitIssueAnalyser.java:67)
	at staticanalysis.ConventionAnalysisTest.todosMustReferenceAGitIssueInOpenStateOnly(ConventionAnalysisTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at io.github.tjheslin1.westie.infrastructure.FileLinesReader.readAllLines(FileLinesReader.java:37)
	at io.github.tjheslin1.westie.infrastructure.WestieCachedFileReader$1.load(WestieCachedFileReader.java:68)
	at io.github.tjheslin1.westie.infrastructure.WestieCachedFileReader$1.load(WestieCachedFileReader.java:65)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	... 39 more
```

**Comment by tjheslin1** [comment]
All addressed in [release 1.4.2](https://github.com/tjheslin1/Westie/releases/tag/1.4.2)
